In [1]:
import pandas as pd

In [2]:
df=pd.read_excel(r"C:\Users\Administrator\Desktop\train.xlsx", names=["comment","tpoic"])
df

                                                comment      tpoic
0     A few things. You might have negative- frequen...    Biology
1     Is it so hard to believe that there exist part...    Physics
2                                        There are bees    Biology
3     I'm a medication technician. And that's alot o...    Biology
4                        Cesium is such a pretty metal.  Chemistry
...                                                 ...        ...
8690  I make similar observations over the last week...    Biology
8691                                    You would know.    Biology
8692            Also use the correct number of sig figs  Chemistry
8693  What about the ethical delimmas,  groundbreaki...    Biology
8694                          I would like to know too.    Biology

[8695 rows x 2 columns]

In [3]:
df.shape

(8695, 2)

In [4]:
df.columns.tolist()

['comment', 'tpoic']

In [5]:
df["tpoic"].unique().tolist()

['Biology', 'Physics', 'Chemistry']

In [6]:
df["comment"].value_counts()

comment
[removed]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    114
[deleted]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     65
Thank you!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     7
Thank you                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      5
Thanks!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
First off, matter can absolutely be created and destroyed. Just not at standard conditions. This is part of what high energy physics deals with. For example, there was a recent experiment at the LHC where photons (massless particles) were merged into bosons (massive particles).\n\nYou are asking about the [carbon cycle](https://en.wikipedia.org/wiki/Carbon_cycle). Inorganic carbon, in the form of carbon dioxide, is extracted from the environment, reduced and fixed into organic matter primarily through photosynthesis. Cells do this by harnessing an enthalpy gradient to lower entropy.\n\nIf you are asking where all the carbon on Earth comes from - it was generated in stars on the main sequence, from hydrogen, via [nucleosynthesis](https://en.wikipedia.org/wiki/Stellar_nucleosynthesis). We have a fixed and constant amount of carbon.      1
Thank You - If I assumed it was an electric heater, what would the formula be?\n\nYou are correct, and though this is a sealed propane fireplace, the 50,000BTU of the burner, looses 32% of itâ€™s efficiency due to the chimney.\n\nAlso the reason for the question is I have a â€˜newâ€™ fireplace installed, that is higher BTU than the old, yet yields no  heat. The manufacture and installer and distributer all were over today, filling the air with techno-garbo of why I should expect a 50,000 BTU fireplace to NOT HEAT A ROOM very well.\n\nI did the math 50,000x68%=34,000 BTU actual heat. Now to demonstrate the lack of heat, I converted this to Watts then showed a 1500watt electric heater was hotter than the fireplace. \n\nWhat I would like to show a theoretical heat transfer in temperature gain.\n\nThanks agin for the time                  1
You would know.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
Also use the correct number of sig figs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
I'll check it out.  \n\nI do like Carlo Rovelli's "The Order of Time".  Have you had a look at that?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
Name: count, Length: 7948, dtype: int64

In [7]:
df.isnull().sum()

comment    2
tpoic      0
dtype: int64

In [8]:
df=df.dropna()

In [15]:
df = df.dropna(subset=['comment'])

In [16]:
df['comment'] = df['comment'].fillna("")

In [17]:
df['comment'] = df['comment'].astype(str)

In [18]:
df = df.rename(columns={'tpoic': 'topic'})

In [19]:
df = df.dropna(subset=['comment'])
df['comment'] = df['comment'].astype(str)

In [21]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

corpus=[]
for i in range(len(df)):
    rp=re.sub('[^a-zA-Z]'," ",df['comment'][i])
    rp=rp.lower()
    rp=rp.split()
    rp=[ps.stem(word) for word in rp if not word in stopwords.words('english')]
    rp=" ".join(rp)
    corpus.append(rp)

In [22]:
corpus

['thing might neg frequenc depend select go least common phenotyp reflect genotyp go advantag environ instanc prey anim vole light dark phenotyp predat might recogn common phenotyp food light vole common fox may keep closer eye light phenotyp vole recognis good prey would reduc light caus allel due increas predat dark genotyp would increas proport popul scenario revers cycl continu perpetu n nhowev unlik strictli yearli usual take time year entir popul allel frequenc chang enough make larg enough differ alter fit n nmore like year year basi popul experienc fluctuat select altern condit environ favor one genotyp anoth perhap plant speci live area flood everi year two phenotyp popul plant much better dryer year one better wet year flood dri type genotyp fit lead offspr therefor dri allel popul howev flood year wet like phenotyp better propag wet gene',
 'hard believ exist particular detect anyth invent far n ni mean look long took human find way detect radiat',
 'bee',
 'medic technician alot drug liver probabl die immedi fine take care self tho definit good bodi',
 'cesium pretti metal',
 'meant question unclear',
 'shove ass see happen',
 'mean butter besid sugar bake soda peanut yeah',
 'http joinchat gellhlumcxhngi',
 'well thing realli induc immun respons introduc protein alreadi',
 'h produc egg protein denatur titrat basic solut like naoh would allow determin amount h henc amount denatur protein think correct school lab access fanci equip',
 'mrna would specif protein tag allow enter nucleu even integr dna covid vaccin mrna enter nucleu far awar',
 'probabl realli torn dragonfli',
 'help valu tho',
 'free elect call lone pair see http en wikipedia org wiki lone pair valenc electron part coval bond molecul n nthe alien face essenti reminisc spatial distribut lone pair sinc p orbit electron http www chemtub com orbit p undergo spx hybrid http en wikipedia org wiki orbit hybridis contribut coval bond n nhowev lone pair form bond exampl lone pair oxygen water undergo hydrogen bond http en wikipedia org wiki hydrogen bond hydrogen',
 'post brought vinegar clean good',
 'realist better buy new one ebay amazon rock auto probabl get need',
 'hey get one day',
 'also gloriou spi devic use laser rangefind window vibrat peopl talk bounc window vibrat allow remot listen',
 'gill collaps air stick togeth ga exchang surfac area layer moistur keep conduct gill collaps air dri inhibit ga exchang',
 'funni video hate ad read mid video rather wait til end wonder get paid middl',
 'would definit use mcguever episod',
 'molecular siev far wors test magnesium get ppm ms get ppm water determin karl fischer titrat',
 'sure need know charg fe guess need know first two group last two includ nobl gase plu middl alway charg could wrong n nedit typo',
 'need exorcist',
 'sound awesom would total love tri even version almond',
 'absolut f kind question comment guy waaaaay much time hand',
 'titl pretti garbag mention singl thing physic n nthe physic question b anomali new measur came actual consist theori expect sig side anomali guarante side mean anyth sinc differ channel certainli suggest',
 'would love formula websit calcul x x room need btu rais temperatur f normal insul n nso unit creat temperatur chang f btu effect heat n nthink got someon formula would prefer websit',
 'lol kinda look like bladder',
 'beaver eat fish',
 'ye sorri even realli clear whether percepta compani acd lab compani percepta product percepta platform host product n ntl dr ye',
 'probabl perchloroethylen wide use much less nowaday n nhttp nj gov health eoh rtkweb document fs pdf',
 'wether softwar exist sure would rel easi program would surpris one done yet n nvisual h bond acceptor lone pair n f h bond donor hs bound n f gener speak cours alway except ask question assum need worri n nr chemhelp futur refer',
 'mix whatev make go boom find',
 'lot good advic alreadi differ idea think ahead time want degre want phd want work lab get law degre teach industri help know import work toward focu',
 'remov',
 'potato',
 'silli comment delet short n nbut burn flesh',
 'expect differ kind trip cool',
 'scienc dmt tattoo',
 'next gener star trek',
 'ok send pm soon find exact assign pc',
 'one care one forc live healthi cuz freedom dude',
 'photon reflect get absorb',
 'think unjustifi idealist view scienc work depend enorm amount good faith scientist deliber deceiv us n nexperiment data like ambigu abl object analyz understood particular context experiment apparatu scientist construct oper like imag process someth write math anybodi run comput publicli avail dataset dna sequenc protein fold result pile number make sens believ said apparatu n ni complet agre dia look good give crappi justif share data share data hirsch go solv anyth',
 'delet',
 'live societi',
 'year ago articl young doubl slit experi inspir entir journey love physic write scienc fiction heard quantum eras experi video explain well thank sabin hossenfeld tackl yet anoth mystifi fascin topic even know exist',
 'ok retard',
 'law enforc pepper spray flammabl taser compat govern regul therefor look follow non exhaust law enforc brand exampl deftec aka first defens sabr red dp fox lab pepper enforc punch ii capstun vexor ect',
 'thank also found lectur n nhttp youtu umzdnyriato',
 'conscious opinion notic aliv control bodi understand bodi whole integ entiti say babi think without consciou think consciou process conscious think well think intent like dog would intent move leg feel consciou inde think anim includ insect consciou human sens well awar integ entiti control',
 'start find molecular formula start compound',
 'signific h c number bro',
 'may come handi http libgen search php req critic survey stabil constant edta complex lg topic libgen open view simpl re phrase column def',
 'sound perfect thank',
 'read attach receptor much mu',
 'dithian sure',
 'pose everi day',
 'make pyridin n oxid',
 'metabol pretti big deal',
 'rotor wash must extend way ground support weight machin n nwhat',
 'albert einstein',
 'engin',
 'crank ton opioid peptid undergrad somewher neighborhood fentanyl term mu affin',
 'sure univers mine first year big turn well interest cell gene nitti gritti stuff rather popul behaviour ecolog etc go scientif method suggest look ahead cours univers offer get nd rd th year becom special find cours want take like immunolog cell biolog molecular scienc genet etc n na job though hard get one bachelor imposs would like want special get master atleast phd wanna go small town may also need go big citi research job',
 'guess feromon wood ball resin',
 'depend strong floor',
 'x ray radio wave em spectrum',
 'googl dilut hope lessen concern',
 'believ zinc air batteri sometim use hear aid',
 'electron',
 'never understood peopl share note use googl drive student class could upload note interest articl etc share googl doc class peopl could write collabor',
 'calcium milk help prevent lead absorb bodi accord hsahealth com',
 'lol exactli',
 'e hem work secret research fli facil prize win indestruct fli escap data collect pin point locat team move shortli make sudden movement destruct person properti apprehend fli fulli compens',
 'would homosexu act',
 'option global fit paramet analysi time consum difficult especi sinc need proper de correl variou experiment theoret uncertainti sourc input analysi n nthere effort sphere statist probabl prerequisit say anyth meaning right',
 'like color choic',
 'burn ye',
 'team call snail buddi call team less shame',
 'corpor need find differ two pictur n nme pictur',
 'know braver man',
 'remov',
 'reson',
 'remov',
 'hope burn',
 'gave ugli p star',
 'start man',
 'thought along line read question could could suppos could realli improperli contain',
 'know spent last year leran molecular orbit theori gonna need mix liquid liquid b centrifug puppi minut repeat hour golli pay hour call day work n nall realli need noodl ged push button',
 'sent chat sinc send messag',
 'ghostli pink stuff ghost buster',
 'ye call gluconeogenesi',
 'well yeah',
 'routin sequenc genet modifi sampl ensur intend modif occur whether target edit see gene need produc ca guid rna genom probabl',
 'look like starcraft zerg charact',
 'giancoli good start pb spacetim actual realli bad',
 'mark nsfw im ctfuuuu',
 'forbidden strawberri vanilla ice cream',
 'bruh',
 'multipl light bulb',
 'boat appli variou research grant help us fund project like share resourc use',
 'dont think amino acid deriv normal take form phosphocreatin use process convert adenosin diphosph adp adenosin triphosph atp cell use energi donat phosphat group adp n ncreatin one research supplement look u wanna know',
 'sale market either push pill big pharma make develop market',
 'cours yep australia',
 'well water made hydrogen oxygen gase dissolv water well look soda drink co water full could inhal water get tini tini tini fraction oxygen would abl keep demand water act irrit lung structur suit deal get oxygen water get water lung easi much get order take anoth breath need get drown keep demand would need breath ungodli amount water per second get enough oxygen lung',
 'remov',
 'op want let know websit ip restrict cannot open websit outsid us use vpn open anyway littl add headlin',
 'think starship trooper describ',
 'tast like',
 'best advis invest hot plate magnet stir distil equip basic anyth buy beaker n nit cost get set need anyth els look youtub inspir experi uk care buy make lot chemic illeg without licenc',
 'homo sapien primari evolutionari nich highli social pack anim tool use one argu first human pick stick built sack food use technolog ergo never develop tool use homo sapien would like overcom interbr homo neanderthalensi also develop tool use social pack behavior member homo genu would like sapienc intact outlook world might differ n nevolut advanc best suit nich human hagfish equal well evolv nich fact hagfish may consid highli evolv due note human difficulti biped fact hagfish design chang million year work well n nalso play eugen base moral e g deserv live technolog absent ubermensch fantasi good look regardless age',
 'ok paramecium conjug includ plasmogami karyogami say',
 'remov',
 'fuck atom wrong fuck wrong sens know look like go shill nft crap somewher els',
 'u go n n nhttp www khanacademi org scienc physic linear momentum elast inelast collis elast inelast collis text elast collis conserv quantiti elast collis text collis perfectli elast energi lost',
 'small idea told bemefici later job market studi abroad internship abroad ncompani seem solid peopl vita',
 'correct ye n nif dilut strong acid time becom similar acid weak acid',
 'estoy haciendo tercero semestr supongo',
 'europ dont touch poison mushroom',
 'ok mention intricaci gener rel answer layman level question sweat',
 'green flame',
 'got thing littl backward need concentr final dilut part stock part total henc therefor part stock part dilig water make ml solut n nthe rest backward',
 'realli sure dont know enough life phd tri find option',
 'fals alarm think thermomet actual galinstan',
 'sound like realli solid shot consid improv make sure applic acknowledg previous poor grade highlight impress improv make strong stori person statement also make sure recommend speak practic research skill learn ask mention certain part experi work think specif exampl particularli insight recommend person statement import',
 '',
 'well fair total irrevers hyperbar oxygen therapi save',
 'make sens n nif vibrat would play role would absolut crush floor time larger earthquak n nthere noth would make vibrat stronger nowher absolut noth magnet amount vibrat would caus anyth look like graviti n n n scientist french atom energi comiss set hydrogen k simul low graviti introduc high speed low amplitud vibrat restor effect graviti n nthat make sens idea refer misunderstand experi complet',
 'eleg littl beetl',
 'ca nitrat react sulphur drop caso also work ba',
 'may ask year first year want research think take first year third year',
 'neutrino pass right',
 'look way much like quiz test question',
 'ye think agre second scenario depend bodi react upon ad extra weight left handl instinct tilt bike right depend posit torso one singl solut bike angl torso angl keep center mass right place',
 'get p chem',
 'well anoth neutrino like particl ad rest would super mundan realli chang current conceptu understand graviti particl physic mond would suddenli make gener rel consid one beauti theori physic clear stori arc conceptu deriv wrong replac someth appear total arbitrari cludg togeth cours mayb futur someon come better motiv relativist mond',
 'poseidon kiss come littl extra',
 'realli chang anyth n nall would mean speci previous thought extinct would found still around n nand alreadi know speci period gone basic unchang n nspong exampl think oldest known anim still today n nin term would studi probabl thing alway studi gain energi reproduc anim taxonomi stuff like',
 'thank pro tip drop',
 'umbra name darkest shadow name phenomenon',
 'see ratio k k mode statist uncertainli theori expect larg uncertainti anyth happen still nice see side',
 'long till start see cyborg',
 'see thank',
 'well actual ask whether natur enzym product would decreas took n nalso could expand interject list',
 'crazi talk surviv rate much scare',
 'love feynman lectur topic interest learn http www feynmanlectur caltech edu html http www feynmanlectur caltech edu html n nthe essenti idea energi realli tangibl thing mathemat quantiti alway conserv realli mean anyth concret use tool calcul',
 'ck advanc biolog concept nhttp www ck org book ck biolog advanc concept section n nsection n nnot sure qualifi comprehens go refer end section pretti decent start',
 'punch brain ye thank let know eas mind bit glad good',
 'kind drink store bottl also know materi bottl',
 'thank ill tri tomorrow',
 'oh sorri',
 'compar photo http gardentherapi ca common air plant varieti',
 'build beta detector found fpga adc use let program unless bodg work board good solder want accident break v expens board',
 'saludossssssss',
 'tf play sigma role',
 'http www ncbi nlm nih gov pmc articl pmc nhttp pubm ncbi nlm nih gov n nthese scienc version eli freshman bio n nmost gene therapi use someth call viral vector put blueprint want specif cell start make miss usual sinc inher virus immun system think regular bad one start attack',
 'buy preciou metal silver gold worri',
 'submit physic gre score grad school applic sinc school made option year n n pretti averag know help hurt weak point applic gpa amount physic relat research experi one solid physic reu report also done good amount research that relat physic also think recommend pretti good n nwhat lowest gre score would report',
 'thing spend k biolog degre',
 'delet',
 'ignor consider practic problem engin nuclear reactor insid someon stomach convert gain biolog use energi funnili enough pick iron mayb purpos get next level whoosh iirc element alway energi loss whether put nuclear fusion fission unfortun dream eat iron surviv dead',
 'oh hey mum say said hi',
 'barium',
 'well hipster beard filthier toilet seat n nye studi',
 'damn interest suppos also superconduct higher temperatur mayb',
 'idk anyon said yet think dragon fli walk use leg land thing less issu',
 'seem dilut probabl need run concentr use catalyt pot carb',
 'actual boy u way critic repli help know everyth everyon mention far ask gener answer specif question',
 'best advic menor stay top thing studi day',
 'yep probabl gonna',
 'didnt know hell w go know innoc',
 'someon fuck great job honestli baffl',
 'thank lot',
 'remov',
 'imposs us know everyth incomplet theorem',
 'edg',
 'ye get easier read learn part ignor scan read understand vocabulari becom second languag read paper minut howev alway paper either challeng want spend time also initi everybodi hate read stick fine',
 'contain impur often use reagent grade versu food grade water feed bacteri growth',
 'better sub type thing',
 'shadow ombr',
 'think converg point n nfor last one neutrino mass well establish mani mani sigma good agreement call solar paramet solar oscil measur sno borexino superk other long baselin reactor measur kamland former measur improv consider dune latter juno call atmospher paramet show even impress agreement atmospher measur superk icecub long baselin acceler measur mino nova k medium baselin reactor measur daya bay reno paint clear pictur neutrino oscil guarante least two mass n nwhat mass look like model build point view fact lot option exactli neutrino repres biggest open question particl physic almost certainli dirac mass term yukawa coupl higg field rest fermion guarante least two new gaug singl e right hand steril neutrino stori obvious complic sinc know lepton number good symmetri also majorana mass term presum addit fermion gaug singlet n nof cours model builder develop mani interest model give neutrino mass includ right hand neutrino includ sever addit particl anyway',
 'say molecular weight somewher one anhydr',
 'common pretti much nail last sentenc student right brain prefer creativ fluiditi orgo contrast left brain prefer black white quantit qualiti gen chem usual think left right brain math scienc art creativ respect organ one scienc much artist other actual draw sens artist thought process requir conceptu gen chem math black white pattern base subject reli conceptu outcom',
 'good pb space time episod cpt symmetri time case individu symmetri broken n nhttp www youtub com watch v l idut tkeq',
 'heard exot matter fill univers invis would slow almost hit light speed get faster ncan give link proof right heard german professor tv speak german tell send link',
 'pibbl sweetest dog go bad dog bad owner n non p agre n n sorri hear die laughter first choic n nhaha actual funni n n cheer n nto clairifi never claim wrong unnecessarili explain someth need explain right say gender sex say assist esl learner unwelcom perhap even overli sensit fell like time place neccesari condo bird photo may place n neither way hard feel',
 'came say challeng internet would one believ',
 'chemistri degre',
 'ratio number number cubic cm cubic',
 'look like show tricki identifi wood frog seen speci mention australia later stripe even though similar mayb see found countri thank lot',
 'curv curv around sun instead curv plane',
 'point liter one',
 'thank agre',
 'yeahhh gonna go real',
 'actual like boob',
 'judg text assum first one',
 'awesom',
 'differ virus caus cold virus mutat even immun one one could mutat express differ protein differ mode infect n nlook way could liter die common cold immun system zero memori capabl adapt quick actual pretti good job',
 'roman year ago present photo would exclaim umbra n nthere word phenomenon n n nhttp www readingrocket org articl root word root affix',
 'avail campbel biolog concept connect th edit ebook http www ebook com product page campbel biolog concept connect th edit',
 'napalm trick',
 'bout oxid number',
 'never read past first sentenc owe shit anim grow stupid question',
 'thank got isopropyl alcohol empti plastic spray bottl need sanit spray bottl fill',
 'appreci comment dont want sound rude think mrna vaccin cannot refer basic vaccinn top guess deep insight cellular interact mrna vaccin havent discuss cours studi gener mdr least live germani consid famili doctor daili routin wihtout keep latest scientif research',
 'salt ion trench coat n nhow fuck dare',

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=None)
X=cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [25]:
X.shape

(8693, 11949)

In [26]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df["topic"]=le.fit_transform(df[["topic"]])
df["topic"]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0       0
1       2
2       0
3       0
4       1
       ..
8688    0
8689    0
8690    1
8691    0
8692    0
Name: topic, Length: 8693, dtype: int64

In [28]:
y=df["topic"]

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,train_size=0.8,random_state=True)

In [30]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [31]:
ypred_train=model.predict(X_train)
from sklearn.metrics import accuracy_score
accuracy_score(y_train,ypred_train)

0.8377911993097498

In [33]:
ypred_test=model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,ypred_test)

0.7320299022426682

In [36]:
from sklearn.model_selection import cross_val_score
cross_val_score(model,X,y,cv=5).mean()

np.float64(0.7321983786298357)

In [37]:
input_comment =" "

In [39]:
df_test =pd.DataFrame({"topic":input_comment},index=[0])
df_test

  topic
0

In [41]:
corpus=[]
for i in range(len(df)):
    rp=re.sub('[^a-zA-Z]'," ",df['comment'][i])
    rp=rp.lower()
    rp=rp.split()
    rp=[ps.stem(word) for word in rp if not word in stopwords.words('english')]
    rp=" ".join(rp)
    corpus.append(rp)

# test vectorization
X=cv.transform(corpus).toarray()

In [49]:
# prediction
pred = model.predict(X)

if pred[0] == 0:
    print("biology")
elif pred[0] == 1:
    print("physics")
else:
    print("chemistry")

biology